version: 0.2

phanse:
  install:
    command:
      # install Node 16
      - echo Installing node 12 ....
      - curl -sl https://deb.nodesource.com/setup_16.x | bash -  
      - apt-get install -y nodejs
      # install Yarn

  pre_build:
    command:
      # install dependencies
      - echo installing npm i ...
      - npm i
  
  build:
    command:
      - echo build creating ...

artificats:
  files:
    - "**/*"    

